### ISSUE TITLE
Error "Invalid ruleset provided"

### ISSUE THREAD

**Issue by kkeck-nordlb** [SchwarzIT/api-linter-rules#22]
Hi,

I've installed and configured the Spectral plugin in **IntelliJ** on **macOS** as follows:
**Ruleset**: https://github.com/SchwarzIT/api-linter-rules/blob/main/spectral.yml
**Included** files: **.yml

The linting fails with the following errors. I've tried an alternate ruleset file as well, unfortunately with the same results:

```
13:52	Linting failed
			Execution of Spectral failed using the following command: ""/Users/myuser/Library/Application Support/JetBrains/IdeaIC2021.3/plugins/spectral-intellij-plugin/spectralExecutables/spectral-macos" lint --format json --ruleset https://github.com/SchwarzIT/api-linter-rules/blob/main/spectral.yml /var/folders/jy/wp8k1n1d0nx2kqtt6tlfrs5c0000gn/T/5251202261066929309.tmp"
			Error Message:
			Invalid ruleset provided
```

Can you please look into this? Many thanks in advance!

**Comment by markbrockhoff** [comment]
Hi @kkeck-nordlb, it looks like you're using an invalid url for the ruleset.
If you try to open the link to the ruleset you're using, you'll see that it sends you to the github page of that file.
Since that's a website so basically HTML, spectral is not able to understand the ruleset. (It's even more noticable when you curl the url)
You need to use the url of the "raw" file hosted on github. For example: https://raw.githubusercontent.com/SchwarzIT/api-linter-rules/main/spectral-api.yml
If you navigate to this link you'll see, that everything github related is gone and you're just served the raw yaml file.
We have all the urls of our spectral rulesets in our readme, you can just copy them from there ;)

Please try again with this url and let me know if it solves the issue: https://raw.githubusercontent.com/SchwarzIT/api-linter-rules/main/spectral-api.yml

**Comment by kkeck-nordlb** [comment]
Hi @markbrockhoff. Yes, of course that was the problem - many thanks for the hint!
